[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["functions/**/*"]
  external_node_modules = ["express", "mongoose", "multer"]

[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400" 